Update PHPUnit to 9.1
Nekland/Woketo pull request #160
Opened 2020-12-07 00:31 UTC by shuchkin

<img width="281" alt="Screenshot_294" src="https://user-images.githubusercontent.com/315872/101297930-a7970500-3855-11eb-8cb0-b33f8e81739c.png">

Update PHPUnit to 9.1
Update react/dns to 1.x

2021-03-18 22:08 UTC, Nek- approved these changes
This is great. How did I miss that? Thanks.

2021-03-18 22:08 UTC, Nek- commented on composer.json
> +        "react/dns": "^1.0"
This looks great, other versions were good.

2021-03-18 22:08 UTC, Nek- commented on composer.json
> +        "ext-soap": "*"
soap is definitely not required :) .

2021-03-18 22:21 UTC, Nek- requested changes
Sorry I though I would be able to push to your PR but I'm not, please change what I noticed. 🙏

2021-03-19 11:22 UTC, shuchkin commented
check it

2021-03-19 11:38 UTC, Nek- approved these changes

2021-03-19 11:38 UTC, Nek- commented
@shuchkin for your information, `^1.0` is the same as `^1.0.0` :) . But nvm lets go for it.

2021-03-19 11:38 UTC, merged